/*
 * AiDevelopmentInsights — a coach-style AI summary of the athlete's trajectory
 * plus a short list of AI recommendations. The headline summary "regenerates"
 * (cycles through cosmetic variants) on demand to feel generative. NO API calls
 * — all text is canned. Respects prefers-reduced-motion (the regenerate shimmer
 * is motion-safe only).
 */
import { useState } from "react";
import { Brain, Sparkles, RefreshCw, Target, TrendingUp, CalendarCheck } from "lucide-react";
import { AiCard } from "./AiCard";

/** Cosmetic generated summaries — cycled by the regenerate control. */
const SUMMARIES = [
  "Maya is trending in the top 12% of her age group for shooting development this season. Her finishing off the catch jumped two grade-levels in eight weeks, and her practice consistency is now a strength. The clearest unlock next: free-throw repeatability under fatigue.",
  "The model sees a clean upward curve across Maya's core skills — ball-handling and basketball IQ are compounding fastest. Defensive closeouts are the one area lagging the trend line; a targeted block here would lift her overall projection by an estimated 6%.",
  "Strong week. Maya's effort metrics (reps, attendance, film views) all sit above her season baseline, which historically precedes a skill breakout within 2–3 weeks. Keep the current load steady — she's in the sweet spot, not over-extended.",
] as const;

/** Ranked AI recommendations (cosmetic). */
const RECS = [
  { icon: Target, text: "Add 50 free throws after each session to lock in repeatability under fatigue.", tag: "High impact" },
  { icon: TrendingUp, text: "Schedule one extra defensive-closeout drill block this week to balance the curve.", tag: "Quick win" },
  { icon: CalendarCheck, text: "Maya is ready to move up to the 11U skills clinic — confidence 88%.", tag: "Milestone" },
] as const;

function prefersReducedMotion() {
  return typeof window !== "undefined" && window.matchMedia?.("(prefers-reduced-motion: reduce)").matches;
}

export function AiDevelopmentInsights() {
  const [idx, setIdx] = useState(0);
  const [shimmer, setShimmer] = useState(false);

  function regenerate() {
    if (prefersReducedMotion()) {
      setIdx((i) => (i + 1) % SUMMARIES.length);
      return;
    }
    setShimmer(true);
    window.setTimeout(() => {
      setIdx((i) => (i + 1) % SUMMARIES.length);
      setShimmer(false);
    }, 550);
  }

  return (
    <AiCard
      icon={Brain}
      pillIcon={Sparkles}
      title="AI development insights"
      subtitle="A generated read on Maya's trajectory · this season"
    >
      {/* Generated summary */}
      <div
        aria-live="polite"
        className={`mt-5 rounded-2xl border border-border bg-secondary/30 p-4 transition-opacity duration-300 ${
          shimmer ? "opacity-40" : "opacity-100"
        }`}
      >
        <div className="flex items-center gap-1.5 text-[11px] font-bold uppercase tracking-[0.2em] text-gold-text">
          <Sparkles className="h-3.5 w-3.5" />
          Coach summary
        </div>
        <p className="mt-2 text-sm leading-relaxed text-foreground">{SUMMARIES[idx]}</p>
      </div>

      {/* Recommendations */}
      <div className="mt-5">
        <div className="mb-2 text-xs font-semibold uppercase tracking-wide text-muted-foreground">
          Recommended next steps
        </div>
        <ul className="space-y-2.5">
          {RECS.map((r) => {
            const Icon = r.icon;
            return (
              <li
                key={r.text}
                className="flex items-start gap-3 rounded-xl border border-border bg-card p-3"
              >
                <span className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-gold-soft text-gold-text ring-1 ring-gold/20">
                  <Icon className="h-4 w-4" />
                </span>
                <div className="min-w-0 flex-1">
                  <p className="text-sm leading-snug text-foreground">{r.text}</p>
                  <span className="mt-1 inline-block text-[10px] font-bold uppercase tracking-wide text-gold-text">
                    {r.tag}
                  </span>
                </div>
              </li>
            );
          })}
        </ul>
      </div>

      <div className="mt-5 flex items-center justify-between border-t border-border pt-4">
        <p className="text-[11px] text-muted-foreground">
          Generated by Aster AI — illustrative. A coach reviews before it reaches you.
        </p>
        <button
          type="button"
          onClick={regenerate}
          aria-label="Regenerate AI summary"
          className="inline-flex shrink-0 items-center gap-1.5 rounded-lg border border-border bg-card px-3 py-1.5 text-xs font-semibold text-foreground transition-colors hover:border-gold/40 hover:bg-gold-soft hover:text-gold-text"
        >
          <RefreshCw className={`h-3.5 w-3.5 ${shimmer ? "motion-safe:animate-spin" : ""}`} />
          Regenerate
        </button>
      </div>
    </AiCard>
  );
}
